### ISSUE TITLE
Tool Labels - Options

### ISSUE THREAD

**Issue by zagorGit** [bio-tools/biotoolsDocs#32]
Is it possible to define custom label, as it seems that some labels defined within 'Browse resources by popular terms' (https://bio.tools/) do not exist anymore in the drop-down menu and some useful are missing?

**Comment by hansioan** [comment]
@zagorGit 
Could you please point out which of them are missing? 
Also, a way of adding "labels" is to add a Collection item (in the tool edit page under the Labels tab)

**Comment by zagorGit** [comment]
Ok, thank you.

I would like that my tool appears in the 'Pathway or network visualisation' subsection (section Other) while browsing https://bio.tools/. Adding it via Collection did not help with it.

I would also appreciate more tags related to Data management, metadata, and FAIR data/sharing. At the moment it reads like the focus is on the databases, or various terms are concatenated within one tag -- not all are necessarily covered with one tool.

**Comment by hansioan** [comment]
@zagorGit 
This is because `Pathway or network visualisation` is an EDAM Ontology concept, see
http://edamontology.org/operation_3083
It seems that this concept has been deprecated in EDAM and thus cannot be used in bio.tools in an easy way.
You can use one or both of
- `Network visualisation`(http://edamontology.org/operation_3925)
- `Pathway visualisation` (http://edamontology.org/operation_3925)

since those are the replacements in EDAM for the deprecated concept  `Pathway or network visualisation`, but this won't make your tool appear in the bio.tools section.
If you do however wish your tool to appear in the section you can still use the deprecated `Pathway or network visualisation` concept, but you will have to add it manually via the JSON tab since it's no longer part of the current EDAM version, but bio.tools supports deprecated concepts if you really need them. If you look in the JSON tab for other operations, you can duplicate the same structure and add the concept.
I added an example below
```
 "function": [
    {
      "operation": [
        {
          "term": "Pathway or network visualisation",
          "uri": "http://edamontology.org/operation_3083"
        }
      ]
    }
  ]
```

If you want I can add the concept for you , just let me know for which tool(s). Also, if the operation is part of a function with input and output you can also let me know of those concepts. Or I can just add the operation for you and you can add the rest of the inputs and outputs.

**Comment by zagorGit** [comment]
Thank you for the elaborated and prompt answer.
